### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by peterampazzo** [cowboy-bebug/app-store-scraper#20]
Hello! Sometimes I do get this error:

```
2020-09-14 21:30:57,012 [INFO] AppStore - Searching for app id
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    app = AppStore(country=c, app_name=selectedApp["id"])
  File "/usr/local/lib/python3.8/site-packages/app_store_scraper/app_store.py", line 47, in __init__
    app_id = self.search_id()
  File "/usr/local/lib/python3.8/site-packages/app_store_scraper/app_store.py", line 171, in search_id
    app_id = re.search(pattern, self.__response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

You can try to replicate this error providing as appId `1511279125` and country `AF`.
Do you have any hits?

**Comment by cowboy-bebug** [comment]
Hi there,

Sorry for the late response!

I've got the following snippet which seems to be working:
```python
if __name__ == "__main__":
    from app_store_scraper import AppStore

    app = AppStore(country="AF", app_name="StopCovid France", app_id=1511279125)
    app.review(10)
```

```console
% python main.py
2020-09-28 15:47:18,751 [INFO] Base - Initialised: AppStore('af', 'stopcovid-france', 1511279125)
2020-09-28 15:47:18,752 [INFO] Base - Ready to fetch reviews from: https://apps.apple.com/af/app/stopcovid-france/id1511279125
2020-09-28 15:47:37,310 [ERROR] Base - Something went wrong: HTTPSConnectionPool(host='amp-api.apps.apple.com', port=443): Max retries exceeded with url: /v1/catalog/af/apps/1511279125/reviews?l=en-GB&offset=0&limit=20&platform=web&additionalPlatforms=appletv%2Cipad%2Ciphone%2Cmac (Caused by ResponseError('too many 404 error responses'))
2020-09-28 15:47:37,312 [INFO] Base - [id:1511279125] Fetched 0 reviews (0 fetched in total)
```

And there seem to be no reviews for this app ([see](https://apps.apple.com/af/app/stopcovid-france/id1511279125)).
